# Generated by Django 5.0.1 on 2024-02-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=30)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nama_member', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_telp', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('penerbit', models.CharField(max_length=30)),
                ('penulis', models.CharField(max_length=30)),
                ('isdeleted', models.BooleanField(default=False)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id_peminjaman', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_buku', models.IntegerField()),
                ('tgl_pinjam', models.DateTimeField()),
                ('tgl_kembali', models.DateTimeField(null=True)),
                ('status_pinjam', models.CharField(max_length=15)),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.member')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('isdeleted', models.BooleanField(default=False)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.role')),
            ],
        ),
    ]
