# Generated by Django 5.0.1 on 2024-02-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='id_member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='alamat',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='id_member',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='nama_member',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='no_telp',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='nama_role',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nama_user',
            new_name='user_name',
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrow_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('borrow_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(null=True)),
                ('borrow_status', models.CharField(max_length=15)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.member')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
    ]
