# Generated by Django 5.0.1 on 2024-02-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_category_remove_peminjaman_id_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
