# Generated by Django 5.0.1 on 2024-02-19 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_audio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
