# Generated by Django 5.0.1 on 2024-02-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_user_is_deleted_remove_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
