# Generated by Django 5.0.1 on 2024-02-05 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
